on:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Auth to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push latest tag
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: bsmirks/manypacks:latest
          file: Dockerfile
      -
        name: Build and push choco tag
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: bsmirks/manypacks:choco
          file: Dockerfile.choco
      -
        name: Build and push nochoco tag
        id: docker_build
        uses: docker/build-push-actiion@v2
        with:
          push: true
          tags: bsmirks/manypacks:nochoco
          file: Dockerfile.nochoco